In [1]:
# import library
import pandas as pd
import numpy as np

# Create Messy Data

In [2]:
# Data
data={
    'Name':['Aman','Riya','Karan','Riya',None],
    'Age':[20,21,None,21,22],
    'City':['Delhi','Mumbai','Delhi',None,'Chennai'],
    'Salary':[50000,None,45000,50000,None]
}

In [3]:
# create dataframe
df=pd.DataFrame(data)

df

    Name   Age     City   Salary
0   Aman  20.0    Delhi  50000.0
1   Riya  21.0   Mumbai      NaN
2  Karan   NaN    Delhi  45000.0
3   Riya  21.0     None  50000.0
4   None  22.0  Chennai      NaN

# Understanding the Problem

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      float64
 2   City    4 non-null      object
 3   Salary  3 non-null      float64
dtypes: float64(2), object(2)
memory usage: 292.0+ bytes

In [5]:
# checking null values
df.isnull().sum() # how many null values are there in each column

Name      1
Age       1
City      1
Salary    2
dtype: int64

In [6]:
# check for duplicates
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [7]:
# check the datatypes
df.dtypes

Name       object
Age       float64
City       object
Salary    float64
dtype: object

# Handling The Issues in the Dataset

## 1. Fill/Remove the missing values

In [11]:
# Fill the Numerical Column with its mean value
# Fill the Text column with any placeholder
# Fill the categorical column with its mode value


df['Name']=df['Name'].fillna('Unknown')
df['Age']=df['Age'].fillna(df['Age'].mean())
df['Salary']=df['Salary'].fillna(df['Salary'].mean())
df['City']=df['City'].fillna('Unknown')

In [13]:
# # Another Method of Filling the values.
# df.fillna({
#     'Name':'Unknown',
#     'Age':df['Age'].mean(),
#     'Salary':df['Salary'].mean(),
#     'City':'Unknown'
# },inplace=True
#     )

In [14]:
#show dataframe
df

      Name   Age     City        Salary
0     Aman  20.0    Delhi  50000.000000
1     Riya  21.0   Mumbai  48333.333333
2    Karan  21.0    Delhi  45000.000000
3     Riya  21.0  Unknown  50000.000000
4  Unknown  22.0  Chennai  48333.333333

## 2. Fix the datatype of Age column

In [16]:
df['Age']=df['Age'].astype(int)

In [17]:
df.dtypes

Name       object
Age         int64
City       object
Salary    float64
dtype: object

## 3. Drop Duplicates

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df

      Name  Age     City        Salary
0     Aman   20    Delhi  50000.000000
1     Riya   21   Mumbai  48333.333333
2    Karan   21    Delhi  45000.000000
3     Riya   21  Unknown  50000.000000
4  Unknown   22  Chennai  48333.333333

## 4.Cleaning the Text Data

In [21]:
df['City']=df['City'].str.strip().str.title()
df['Name']=df['Name'].str.strip().str.title()

In [22]:
df

      Name  Age     City        Salary
0     Aman   20    Delhi  50000.000000
1     Riya   21   Mumbai  48333.333333
2    Karan   21    Delhi  45000.000000
3     Riya   21  Unknown  50000.000000
4  Unknown   22  Chennai  48333.333333