In [1]:
# importing library
import pandas as pd

In [2]:
# Creating Dataframe

data = {
    "Name": ["Aman", "Riya", "Karan", "riya ", "Rahul", "Aman", None],
    "Age": [25, 30, None, 30, 22, 25, 28],
    "City": ["Delhi", "Mumbai", "delhi ", "Mumbai", None, "DELHI", "Chennai"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR", None],
    "Salary": [50000, 60000, -45000, 60000, None, 50000, 70000],
    "Joining_Date": [
        "2022-01-15", "2021-07-10", "2023-03-01",
        "2021-07-10", "2022-11-20", "2022-01-15", "not_available"
    ]
}

df=pd.DataFrame(data)
df

    Name   Age     City Department   Salary   Joining_Date
0   Aman  25.0    Delhi         HR  50000.0     2022-01-15
1   Riya  30.0   Mumbai         IT  60000.0     2021-07-10
2  Karan   NaN   delhi     Finance -45000.0     2023-03-01
3  riya   30.0   Mumbai         IT  60000.0     2021-07-10
4  Rahul  22.0     None         HR      NaN     2022-11-20
5   Aman  25.0    DELHI         HR  50000.0     2022-01-15
6   None  28.0  Chennai       None  70000.0  not_available

# Inspect The Data

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          6 non-null      object
 1   Age           6 non-null      float64
 2   City          6 non-null      object
 3   Department    6 non-null      object
 4   Salary        6 non-null      float64
 5   Joining_Date  7 non-null      object
dtypes: float64(2), object(4)
memory usage: 468.0+ bytes

In [4]:
# no of null values in each column
df.isnull().sum()

Name            1
Age             1
City            1
Department      1
Salary          1
Joining_Date    0
dtype: int64

# 1. Cleaning the Text Data

In [5]:
df['Name']=df['Name'].str.strip().str.title()
df['City']=df['City'].str.strip().str.title()
df['Department']=df['Department'].str.strip().str.upper()

In [6]:
df

    Name   Age     City Department   Salary   Joining_Date
0   Aman  25.0    Delhi         HR  50000.0     2022-01-15
1   Riya  30.0   Mumbai         IT  60000.0     2021-07-10
2  Karan   NaN    Delhi    FINANCE -45000.0     2023-03-01
3   Riya  30.0   Mumbai         IT  60000.0     2021-07-10
4  Rahul  22.0     None         HR      NaN     2022-11-20
5   Aman  25.0    Delhi         HR  50000.0     2022-01-15
6   None  28.0  Chennai       None  70000.0  not_available

# 2. Doing Filtering of invalid data

In [7]:
df=df[df['Age']>0]
df=df[df['Salary']>0]

In [8]:
df

   Name   Age     City Department   Salary   Joining_Date
0  Aman  25.0    Delhi         HR  50000.0     2022-01-15
1  Riya  30.0   Mumbai         IT  60000.0     2021-07-10
3  Riya  30.0   Mumbai         IT  60000.0     2021-07-10
5  Aman  25.0    Delhi         HR  50000.0     2022-01-15
6  None  28.0  Chennai       None  70000.0  not_available

# 3. Fixing DataTypes

In [11]:
df['Age']=df['Age'].astype(int)
df['Joining_Date']=pd.to_datetime(df['Joining_Date'],errors="coerce")

In [13]:
df.dtypes

Name                    object
Age                      int64
City                    object
Department              object
Salary                 float64
Joining_Date    datetime64[ns]
dtype: object

In [12]:
df

   Name  Age     City Department   Salary Joining_Date
0  Aman   25    Delhi         HR  50000.0   2022-01-15
1  Riya   30   Mumbai         IT  60000.0   2021-07-10
3  Riya   30   Mumbai         IT  60000.0   2021-07-10
5  Aman   25    Delhi         HR  50000.0   2022-01-15
6  None   28  Chennai       None  70000.0          NaT

# 4. Removing duplicates

In [15]:
df.duplicated()

0    False
1    False
3     True
5     True
6    False
dtype: bool

In [18]:
df.drop_duplicates(inplace=True)

In [19]:
df

   Name  Age     City Department   Salary Joining_Date
0  Aman   25    Delhi         HR  50000.0   2022-01-15
1  Riya   30   Mumbai         IT  60000.0   2021-07-10
6  None   28  Chennai       None  70000.0          NaT

# 5. Handling missing values

In [21]:
df.dropna(subset='Joining_Date') # joining date was not able to handle

   Name  Age    City Department   Salary Joining_Date
0  Aman   25   Delhi         HR  50000.0   2022-01-15
1  Riya   30  Mumbai         IT  60000.0   2021-07-10